CREATE TABLE STUDENT(
    ACCOUNT VARCHAR(128),
    PASSWORD VARCHAR(128),
    SID VARCHAR(128),
    SNAME VARCHAR(128),
    SGRADE INTEGER,
    SEMAIL VARCHAR(128),
    IDENTITY VARCHAR(128),
    PRIMARY KEY (ACCOUNT)
);

ALTER TABLE STUDENT MODIFY SGRADE VARCHAR(38);

CREATE TABLE COURSE(
    CID VARCHAR(128),
    CNAME VARCHAR(128),
    DEPARTMENT VARCHAR(128),
    TID VARCHAR(128),
    PRIMARY KEY (CID)
);

CREATE TABLE TEACHER(
    TID VARCHAR(128),
    TNAME VARCHAR(128),
    PRIMARY KEY (TID)
);

CREATE TABLE CONTACT (
    ID VARCHAR(128),
    PHONE VARCHAR(128),
    NAME VARCHAR(128),
    ACCOUNT VARCHAR(128),
    PRIMARY KEY (ID),
    FOREIGN KEY (ACCOUNT) REFERENCES STUDENT(ACCOUNT)
) CREATE TABLE CLASSROOM(
    ROOMID VARCHAR(128),
    NUM INTEGER,
    PRIMARY KEY (ROOMID)
) ALTER TABLE COURSE ADD ROOMID VARCHAR(
    128
);

ALTER TABLE COURSE ADD FOREIGN KEY (ROOMID) REFERENCES CLASSROOM(ROOMID);

# MAKE FOREIGN KEY FROM TABLE COURSE TO TEACHER.TID

ALTER TABLE COURSE ADD FOREIGN KEY (TID) REFERENCES TEACHER(TID);

CREATE TABLE SELERECORD(
    ACCOUNT VARCHAR(128),
    CID VARCHAR(128),
    PRIMARY KEY (ACCOUNT, CID),
    FOREIGN KEY (ACCOUNT) REFERENCES STUDENT(ACCOUNT),
    FOREIGN KEY (CID) REFERENCES COURSE(CID)
);

INSERT INTO CLASSROOM VALUES(
    'R001',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R002',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R003',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R004',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R005',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R006',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R007',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R008',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R009',
    100
);

INSERT INTO CLASSROOM VALUES(
    'R010',
    100
);

ALTER TABLE SELERECORD ADD FOREIGN KEY (CID) REFERENCES COURSE(CID) ON DELETE CASCADE ALTER TABLE SELERECORD MODIFY CONSTRAINT SYS_C008032 ON UPDATE CASCADE;